// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzhyP3xsR1Qc-4fNqmVCKKQgzFRzceWuQ',
    appId: '1:417950284520:web:b751d1916d30b02cf3e75d',
    messagingSenderId: '417950284520',
    projectId: 'ag-crm-b1840',
    authDomain: 'ag-crm-b1840.firebaseapp.com',
    storageBucket: 'ag-crm-b1840.firebasestorage.app',
    measurementId: 'G-1CMLHPRQV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMpTqTF-ZJJkyuyhzX41OE1uXxO5uJVD0',
    appId: '1:417950284520:android:6dba414ce988503bf3e75d',
    messagingSenderId: '417950284520',
    projectId: 'ag-crm-b1840',
    storageBucket: 'ag-crm-b1840.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh1sZCwJ8VNO-ARxqHzJ8HqxIhl-DV4DA',
    appId: '1:417950284520:ios:67465bf09fbdba73f3e75d',
    messagingSenderId: '417950284520',
    projectId: 'ag-crm-b1840',
    storageBucket: 'ag-crm-b1840.firebasestorage.app',
    iosBundleId: 'com.example.agCrmMyadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh1sZCwJ8VNO-ARxqHzJ8HqxIhl-DV4DA',
    appId: '1:417950284520:ios:67465bf09fbdba73f3e75d',
    messagingSenderId: '417950284520',
    projectId: 'ag-crm-b1840',
    storageBucket: 'ag-crm-b1840.firebasestorage.app',
    iosBundleId: 'com.example.agCrmMyadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzhyP3xsR1Qc-4fNqmVCKKQgzFRzceWuQ',
    appId: '1:417950284520:web:0ee8942b0e47de8ff3e75d',
    messagingSenderId: '417950284520',
    projectId: 'ag-crm-b1840',
    authDomain: 'ag-crm-b1840.firebaseapp.com',
    storageBucket: 'ag-crm-b1840.firebasestorage.app',
    measurementId: 'G-H368615SGV',
  );
}
